### ISSUE TITLE
updateVerifier should be timelocked

### ISSUE THREAD

**Issue by fubuloubu** [tornadocash/tornado-core#45]
In case of the proving system having an issue and needing an update (or to add new features), there is a function called `updateVerifier` that can be invoked by the `operator`.

https://github.com/tornadocash/tornado-core/blob/cfaf325c47c7d3cd542e3ed97e130e12468710b5/contracts/Tornado.sol#L116

This function should probably be time-locked, so someone who has the operator keys (potentially by thieving them) can't unilaterally change the proving system and find some way of stealing the funds.

**Comment by poma** [comment]
The smart contract code is already deployed and is immutable so we can't change that on live version. However, it will be irrelevant once trusted setup is complete (which takes longer than expected due to audit delays) and the operator permissions are transferred to zero address. Also currently the operator is controlled but multisig, so the potential attacker would have to steal multiple keys.

**Comment by fubuloubu** [comment]
Just wanted to put it on the radar. _People_ were angry on Twitter :rofl:

What is the mitigation strategy if the circuit is found to have an issue? (e.g. Zcash inflation bug)

**Comment by poma** [comment]
> What is the mitigation strategy if the circuit is found to have an issue? (e.g. Zcash inflation bug)

Once we release control of operator key, there is nothing we can do that a regular user can't. In case of a critical issue that allows to drain funds hopefully we can discover and exploit it first to migrate funds to a fixed version of the contract. Otherwise we can only warn users and suggest them to withdraw their notes.

**Comment by fubuloubu** [comment]
There's still other options for a mitigation strategy. I think it's important that those options wouldn't allow a unilateral withdrawal by unauthorized accounts (obviously), but something along the lines of a non-ZKP mechanism to conduct a withdrawal (like a way to reveal the secret that ties it to your withdrawal address) coupled with a way to permanently disable the Verifier so it can't be exploited. There's also the matter of contract risk, although the contract system seems simple enough it shouldn't be a huge deal.

It's up to you to figure out if you want a mitigation strategy built in (you might have good reasons not to have any privilege over the system), but I think a lot of people who aren't hardcore decentralists would appreciate that there is some strategy for stopping an attack on their funds and besides hoping to white hat it. It would give people more confidence in Tornado.

**Comment by rstormsf** [comment]
@fubuloubu quite opposite. People are angry that we have this mitigation for now and they are screaming for removal as soon as possible. They even gave us a deadline - 1 month or they will keep screaming on twitter.
So, something that we don't have control over(security audit of MPC) we have to get it done in 1 month.

**Comment by fubuloubu** [comment]
Some days, I realize that Satoshi really had it right. Just drop the code and disappear, before people start to get angry that you made it work in the first place.

It's a very difficult situation you've been put into, I'm sorry you have to deal with it.
